### PR TITLE
3896: Fix filters chip flickering

### LINKED ISSUE #3896: Map ~ Filter and selected filter name disappear briefly when swiping the list
### Describe the Problem
The filter button and the selected filter name briefly disappear when swiping down from the fully expanded list.

### Describe Your Preferred Solution
The filter button and the selected filter name should always remain visible and should not disappear while swiping.
-> Similar to Web App

### Additional Information

https://github.com/user-attachments/assets/5a57acb0-f046-4b08-ae88-90a106be71bf

### PR DESCRIPTION
**Pull request by lunars97**
### Short Description

This PR fixes flickering of the filters chip in maps when the bottom sheet expands and contracts to previous state. Also added `accessible` prop to OpeningHoursListitem.ts to wrap weekdays with hours for screenreader, without it they are read separetely

### Proposed Changes

- [x] remove unmounting condition which was before used to hide the children from the screen reader focusing on them when the bottom sheet expanded. Always keep them mounted.
- [x]  fix accessibility issue when using keyboard with screen reader available by hiding it from screen reader when the modal appears and the bottom sheet expands 
- [x] add accessible prop to weekdays and hours container

### Side Effects

- I hope none

### Testing

1. Go to the maps
2. Expand and contract the bottom sheet
3. See that the filters chip is not flickering (try with additional chips)
4. Also check with screen reader also using the keyboard whether it reads out the children in MapView when the filters modal appear or when the bottom sheet expands

### Resolved Issues

Fixes: #3896 

---

### CODE REVIEW

File: native/src/components/MapView.tsx [hunk 1]
```diff
@@ -217,23 +223,30 @@ const MapView = ({
...
+          accessibilityElementsHidden={bottomSheetFullscreen || modalVisible}>
+          {Overlay}
+        </OverlayContainer>
+        <MapAttribution
+          importantForAccessibility={bottomSheetFullscreen || modalVisible ? 'no-hide-descendants' : 'auto'}
+          accessibilityElementsHidden={bottomSheetFullscreen || modalVisible}
+        />
+        <StyledIcon
+          importantForAccessibility={bottomSheetFullscreen || modalVisible ? 'no-hide-descendants' : 'auto'}
+          accessibilityElementsHidden={bottomSheetFullscreen || modalVisible}
```
Comment (steffenkleinle) [inline native/src/components/MapView.tsx]: 🔧 Can we extract those to shared constants to make this cleaner and remove duplication?

**Review by steffenkleinle — COMMENTED** [review]
Nice work and nice solution!

File: native/src/routes/Pois.tsx [hunk 2]
```diff
@@ -167,6 +167,7 @@ const Pois = ({ pois: allPois, cityModel, route, navigation }: PoisProps): React
         poisCount={pois.length}
       />
       <MapView
+        modalVisible={showFilterSelection}
```
[the remark this answers is not in the document]
Comment (lunars97) [reply native/src/routes/Pois.tsx]: the filter chip and copyright in mapview become inaccessible this way

**Review by steffenkleinle — APPROVED** [review]
Tested on android, works as expected, thanks!

**Review by bahaaTuffaha — CHANGES_REQUESTED** [review]
I can't go back on iOS 26.2:

Image
Image

File: native/src/components/Modal.tsx [hunk 3]
```diff
@@ -47,13 +47,9 @@ const Modal = ({
...
   return (
-    <Portal>
-      <NavigationThemeProvider value={navigationTheme}>
-        <PaperModal
-          visible={modalVisible}
-          onDismiss={closeModal}
-          style={styles.modalStyle}
-          contentContainerStyle={styles.modalStyle}>
+    <RNModal visible={modalVisible} transparent onRequestClose={closeModal} style={styles.modalStyle}>
+      <SafeAreaView style={{ flex: 1 }} edges={['top']}>
```
Comment (bahaaTuffaha) [inline native/src/components/Modal.tsx]: This worked the at first then when I changed tabs then went back to the filter the safe area got broken again.

I think we had that issue before at https://github.com/digitalfabrik/integreat-app/pull/3761
Just use `useSafeAreaInsets()` and add a paddingTop to the view instead until react-native fixes the issue on ios.

**Review by bahaaTuffaha — APPROVED** [review]
Great work!
Tested on iOS and Android. ✅ 

one unrelated issue:
I can't select the filter buttons on iOS while the accessibility inspector is on:

Image

**Comment by lunars97** [comment]
> Great work! Tested on iOS and Android. ✅
> 
> one unrelated issue: I can't select the filter buttons on iOS while the accessibility inspector is on:
> 
> Image

thank you 💚 Hmm regarding the button not reacting on onClick when accessibility inspector is enabled, for me it is working as intended on iPhone 17 Pro simulator... 🤔 

UPDATE: now I got you. Yes, seems like MapView consumes all the focus and it is read as a whole group. I will fix it here in this PR 👍

**Review by bahaaTuffaha — APPROVED** [review]
😃 I can select the filters now with the accessibility inspector on iOS as expected ✅ 
Thanks!! 
can you highlight what you did to make it accessable?

**Comment by lunars97** [comment]
> 😃 I can select the filters now with the accessibility inspector on iOS as expected ✅ Thanks!! can you highlight what you did to make it accessable?

I took the elements above the map container outside of the MapContainer, MapContainer was consuming the focus

**Comment by lunars97** [comment]
@steffenkleinle do you want to give it another round of review due to some changes after your last review? :)

**Review by steffenkleinle — APPROVED** [review]
Code changes look good to me, haven't tested again
