### PR TITLE
3968: [iOS] Fix bottom navigation gap

### LINKED ISSUE #3968: Investigate the space under the bottom navigation on iOS
### Describe the Bug

While scrolling through the page, the bottom navigation bar stays in the same position and leaves a gap underneath.
Device: iPhone 16 Pro (390 × 844 px)
Browser: Chrome.

### Steps to Reproduce

1- Open the web app on an iPhone (Chrome)
2- Go to the main page (also reproducible on other pages).
3- Scroll down.

### Expected Behavior

The bottom navigation bar should stay attached to the bottom of the viewport without leaving any gap while scrolling.

### Related Issues

N/A

### Additional Information

https://github.com/user-attachments/assets/5ed86ed8-e675-453c-8211-a03c33559ee1

### PR DESCRIPTION
**Pull request by bahaaTuffaha**
### Short Description

While scrolling through the page, the bottom navigation bar stays in the same position and leaves a gap underneath.
Device: iPhone 16 Pro (390 × 844 px)
Browser: Chrome.

### Proposed Changes

- used `'env(safe-area-inset-bottom)'` as suggested from this [link](https://www.reddit.com/r/webdev/comments/1lkcn86/looking_for_some_help_with_a_sticky_bottom_bar_on/) similar to our issue.

### Side Effects

- None.

### Testing

⚠️ (I couldn't test this fix because I don't have a real ios device with chrome.)
- Test this fix on a real iOS device with chrome browser and launch the webapp.
- Scroll down to test the bottomNav and how it behaves when the search bar collapses/shrinks

### Resolved Issues

Fixes: #3968 

---

### CODE REVIEW

File: web/src/components/BottomNavigation.tsx [hunk 1]
```diff
@@ -24,6 +24,8 @@ const Container = styled(Paper)({
   right: 0,
   // Positon bottom navigation above bottom sheet
   zIndex: 10,
+  // it removes space under bottom navigation for chrome on iOS
+  paddingBottom: 'env(safe-area-inset-bottom)',
```
Comment (steffenkleinle) [inline web/src/components/BottomNavigation.tsx]: > Where you have: 
``` css
.action-bar {
  bottom: env(safe-area-inset-bottom);
}
```
> You should have just:
``` css
bottom: 0;
```

❓ Doesn't the comment say specifically to change it to `bottom: 0;` though?


```suggestion
  bottom: 0;
```

**Comment by bahaaTuffaha** [comment]
@steffenkleinle I tested the app on chrome on ios:

with the current changes (paddingBottom) it leaves a space like a safe area:
so I will give it a color to match the bottom-nav
Screenshot 2026-04-06 at 1 47 27 PM


but without any changes it looks like this (I cant see a space under):
Screenshot 2026-04-06 at 1 47 50 PM

**Review by steffenkleinle — APPROVED** [review]
Tested on iOS chrome with browserstack, looks good! Couldn't reproduce the original issue either, looked the same as your pictures for me. Thanks for tackling this!

**Review by lunars97 — APPROVED** [review]
I was able to reproduce this issue on a real device, seems like it fixes it. Thank you 👍
