### PR TITLE
4029: Use consistent city name in header title

### LINKED ISSUE #4029: Small city name on city selection
### Describe the Bug

The city name of `Landeshauptstadt München` seems to be quite small when navigating back to the city selection.

### Steps to Reproduce

1. Go to Landeshauptstadt München
2. Click on the city name to go to the city selection
3. See that the city name is a lot smaller and in one line

### Expected Behavior

The city name should be the same size as normally.
Ideally, also in one line as that looks less crowded imo.

### Related Issues

N/A

### Additional Information

Image
Image

### PR DESCRIPTION
**Pull request by steffenkleinle**
### Short Description

Use a consistent city name in the header title, both in size as well as words.

### Proposed Changes

- Always use `cityModel.name` instead of legacy helpers
- Always use the same text variant `subtitle1`
- Rename to title

### Side Effects

N/A

### Testing

Check `Landeshauptstadt München` and navigate to landing.

### Resolved Issues

Fixes: #4029

---

### CODE REVIEW

File: native/src/components/Header.tsx [hunk 1]
```diff
@@ -242,8 +239,8 @@ const Header = ({
         <HeaderBox
           goBack={goBack}
           canGoBack={canGoBack}
-          text={getHeaderText().text}
-          language={getHeaderText().language}
+          title={getHeaderTitle().title}
+          language={getHeaderTitle().language}
```
Comment (bahaaTuffaha) [inline native/src/components/Header.tsx]: How about you call `getHeaderTitle` once and deconstruct it:
```js
const { title, language } = getHeaderTitle()
```

**Review by bahaaTuffaha — APPROVED** [review]
Great work.

Tested on Android and iOS ✅

**Review by lunars97 — APPROVED** [review]
LGTM! Tested on iOS simulator 👍

**Comment by Docmale** [comment]
@steffenkleinle : I see neither a change here nor a problem.

**Comment by steffenkleinle** [comment]
> @steffenkleinle : I see neither a change here nor a problem.

@Docmale see the two pictures on the issue description. The first image says `Landeshauptstadt München` in the header while the second says `München (Landeshauptstadt)` in smaller text. Now it is all `Landeshauptstadt München`.
