### PR TITLE
4058: [iOS] Fix chat input label being shown incorrectly

### LINKED ISSUE #4058: Frag Integreat ~ “My question” label moves and appears crossed out when clicking the input field
### Describe the Bug

When opening the Chat, the label “My question:” is already slightly misplaced.
When clicking into the input field, the label moves up but looks broken (like it is crossed out or overlapped).

### Steps to Reproduce

1. Open the website (integreat.app) on a mobile phone using Safari
2. Go to "Testumgebung"
3. Open the “Frag Integreat” chat and agree to the privacy policy
4. Find the input field “My question”
5. Click inside the input field
6. Watch how the label changes
### Expected Behavior
Label  should stay clear and readable -> No overlapping or crossing lines 

### Environment

- Device/Browser: i phone 12 mini/Safari
- OS version: 26.3.1
- App version: 4.3

### Additional Information

ImageImage

### PR DESCRIPTION
**Pull request by lunars97**
### Short Description

This PR fixes label being shown incorrectly on a textfield when the input is an outlined variant. There is a quick fix for that https://github.com/mui/material-ui/issues/46945#issuecomment-3299699965

### Proposed Changes

- Override mui theme style with a provided suggestion https://github.com/mui/material-ui/issues/46945#issuecomment-3299699965

### Side Effects

- none

### Testing

Check all input fields: Feedback, Search results not found feedback, FragIntegreat chat

### Resolved Issues

Fixes: #4058 

---

### CODE REVIEW

File: web/src/components/ThemeContainer.tsx [hunk 1]
```diff
@@ -127,6 +127,17 @@ const createTheme = (
             },
           },
         },
+        MuiOutlinedInput: {
```
Comment (steffenkleinle) [inline web/src/components/ThemeContainer.tsx:133]: 🔧 For workarounds like this, pls always add an explanation and an link to the issue/suggestion (maybe not both issue links are necessary though):
```suggestion
        // Multiline TextField labels are not displayed correctly on iOS devices
        // https://github.com/digitalfabrik/integreat-app/issues/4058
        // https://github.com/mui/material-ui/issues/46945#issuecomment-3299699965
        MuiOutlinedInput: {
```

Comment (lunars97) [reply web/src/components/ThemeContainer.tsx:133]: yeah, I thought the override itself might be self-explanatory, but this is way is more explicit 👍

**Review by bahaaTuffaha — APPROVED** [review]
Tested on safari and chrome on iOS ✅

**Review by f1sh1918 — APPROVED** [review]

**Comment by kalairubachandrakumaran-oss** [comment]
Tested ✅ 
imageimageimage
